/*
@TargetNode='localhost'
@GeneratedBy=weral
@GenerationDate=08/02/2023 15:23:34
@GenerationHost=ZA-WERAL1777
*/

instance of MSFT_WindowsFeature as $MSFT_WindowsFeature1ref
{
SourceInfo = "C:\\Users\\weral\\Git\\AzureGuestConfigurationDemo\\WindowsIIS.ps1::8::1::WindowsFeature";
 ModuleName = "PSDscResources";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]IIS";
 Name = "Web-Server";
 ModuleVersion = "2.12.0.0";
 ConfigurationName = "WindowsIIS";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="weral";

                        GenerationDate="08/02/2023 15:23:34";

                        GenerationHost="ZA-WERAL1777";

                        Name="WindowsIIS";

                    };
